@extends('layouts.app')

@section('content')

<!-- Terms and Conditions Form -->
<div class="terms-container">
    <form id="terms-form" method="POST" action="{{ route('terms') }}">
        @csrf

        <!-- Decorative Floating Circles -->
        <div class="decorative-circle circle-1"></div>
        <div class="decorative-circle circle-2"></div>

        <h4>Terms and Conditions</h4>

        <div class="terms-list">
            <div class="terms-item animated slideUp">
                <h2>1. Acceptance of Terms</h2>
                <p>By accessing or using the Smoke Sense IoT Smoke Detection System ("Service"), you agree to comply with and be bound by these Terms and Conditions ("Terms"). If you do not agree with any part of these Terms, you may not use the Service.</p>
            </div>

            <div class="terms-item animated slideUp">
                <h2>2. Account Registration</h2>
                <p>To use the Service, you must create an account. You are responsible for maintaining the confidentiality of your account and all activities under your account. You agree to notify us immediately of any unauthorized use of your account.</p>
            </div>

            <div class="terms-item animated slideUp">
                <h2>3. Use of Service</h2>
                <p>The Service allows you to monitor smoke levels and receive real-time alerts. You agree to use the Service in accordance with applicable laws and regulations. You are prohibited from using the Service for any unlawful activities or in any way that may harm the Service or interfere with its operation.</p>
            </div>

            <div class="terms-item animated slideUp">
                <h2>4. User Responsibilities</h2>
                <p>As a user, you are responsible for ensuring that the smoke detectors and other IoT hardware are properly installed and maintained. You must also regularly check and respond to the real-time alerts generated by the Service. You are also responsible for ensuring that your personal information is up-to-date and accurate.</p>
            </div>

            <div class="terms-item animated slideUp">
                <h2>5. Privacy Policy</h2>
                <p>We respect your privacy and are committed to protecting your personal information. Please refer to our Privacy Policy for detailed information on how we collect, use, and protect your data.</p>
            </div>

        </div>
    </form>
</div>

<style>
    /* General styles for the terms page */
    .terms-container {
        max-width: 800px;
        width: 90%;
        margin: auto;
        padding: 20px;
        background: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        position: relative;
        margin-top: 80px; /* Prevent overlap with navbar */
    }

    h4 {
        font-size: 2rem;
        color: #333;
        text-align: center;
        margin-bottom: 20px;
    }

    .terms-list {
        margin-top: 30px;
    }

    .terms-item {
        margin-bottom: 30px;
    }

    .terms-item h2 {
        font-size: 1.6rem;
        color: #3498db;
        margin-bottom: 10px;
    }

    .terms-item p {
        font-size: 1rem;
        color: #7f8c8d;
        line-height: 1.7;
    }


    /* Decorative Floating Circles */
    .decorative-circle {
        position: absolute;
        border-radius: 50%;
        background: rgba(52, 152, 219, 0.1);
        animation: float 6s infinite ease-in-out;
    }

    .circle-1 {
        width: 150px;
        height: 150px;
        top: 30px;
        left: -60px;
        animation-duration: 8s;
    }

    .circle-2 {
        width: 120px;
        height: 120px;
        bottom: 30px;
        right: -60px;
        animation-duration: 10s;
    }

    @keyframes float {
        0% {
            transform: translateY(0) rotate(0deg);
        }
        50% {
            transform: translateY(50px) rotate(180deg);
        }
        100% {
            transform: translateY(0) rotate(360deg);
        }
    }

    /* Slide-Up Animation */
    @keyframes slideUp {
        0% {
            opacity: 0;
            transform: translateY(20px);
        }
        100% {
            opacity: 1;
            transform: translateY(0);
        }
    }

    .animated {
        animation-duration: 1s;
        animation-fill-mode: both;
    }

    .slideUp {
        animation-name: slideUp;
    }

    /* Responsive styles */
    @media (max-width: 768px) {
        .terms-container {
            padding: 15px;
        }

        h4 {
            font-size: 1.8rem;
        }

        .terms-item h2 {
            font-size: 1.4rem;
        }

        button {
            font-size: 1rem;
            padding: 12px;
        }
    }

    @media (max-width: 576px) {
        .terms-container {
            padding: 10px;
        }

        h4 {
            font-size: 1.6rem;
        }

        .terms-item h2 {
            font-size: 1.3rem;
        }

        button {
            font-size: 0.9rem;
            padding: 10px;
        }
    }
</style>

@endsection
